server:
  port: 9999
spring:
  datasource:
    url: database url
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: clientid
            client-secret: secret
